### ISSUE TITLE
Return JSON instead of a JS object

### ISSUE THREAD

**Issue by patcoll** [boopathi/image-size-loader#1]
Then chain with json-loader to get JS object.

Looking for comments.

**Comment by boopathi** [comment]
Though I would like to do a +1 on this, I feel it's not required. Mostly the object will be directly consumed. `JSON.parse()` would be an extra step. But if the user wants a string, he can always,

``` js
var image = JSON.stringify(require('image-size!./file.png'));
```

**Comment by boopathi** [comment]
closed via https://github.com/boopathi/image-size-loader/commit/44498baec5bd40ce416ab0cb4c7ec7e28a31e70b
