### ISSUE TITLE
Does not work with webpack 4

### ISSUE THREAD

**Issue by douglyuckling** [boopathi/image-size-loader#13]
When I try to use this loader with Webpack 4, I get errors like:

<pre>
ERROR in my_image.png (/.../node_modules/image-size-loader!my_image.png)
Module build failed (from /.../node_modules/image-size-loader/index.js):
TypeError: Cannot read property 'context' of undefined
    at Object.module.exports (/.../node_modules/image-size-loader/index.js:36:43)
...
</pre>

The problem is that Webpack 4 doesn't support `this.options.context`, and instead makes the context available via `this.rootContext`. See [webpack 4: migration guide for plugins/loaders](https://medium.com/webpack/webpack-4-migration-guide-for-plugins-loaders-20a79b927202).

When I hack my local `node_modules/image-size-loader/index.js` to make this change, the loader seems to work with Webpack 4.

So I propose the following change, which would get the plugin working with Webpack 4 while retaining support for previous Webpack versions:

```udiff
--- a/index.js
+++ b/index.js
@@ -33,7 +33,7 @@ module.exports = function(content) {
   }
 
   var url = loaderUtils.interpolateName(this, filename, {
-    context: query.context || this.options.context,
+    context: query.context || this.rootContext || this.options.context,
     content: content,
     regExp: query.regExp
   });
```

Would a pull request be welcome?

**Comment by douglyuckling** [comment]
Actually, I just noticed that at least two of the forks of this project have independently added Webpack 4 support (although it looks like at least one may also have dropped Webpack 3 support).

In any case, I should mention that I'm interested in an official release to npm that includes Webpack 4 support, because (in short) in my development environment dependencies on GitHub repositories don't work.

**Comment by boopathi** [comment]
yes. Sure. Send a PR.

**Comment by brmscheiner** [comment]
Just a heads up, I see this issue was closed 2 years ago and the PR went in, but a fresh `npm install` does not include this change. Maybe a new publish to npm is needed?
