### ISSUE TITLE
How to config in my webpack?

### ISSUE THREAD

**Issue by wind4gis** [boopathi/image-size-loader#18]
I want to use url-loader to import the image, however I want to get the size after I get the image, How to config it in my webpack.config.js.

**Comment by wind4gis** [comment]
I use it like `var image = require('image-size!../images/default-backimg.png');`
and it shows
`Error: ENOENT: no such file or directory, open 'D:\WorkSpace\XXX\module.exports = __webpack_public_path__ + "static\media\default-backimg.7fa1c65b.png";'`

**Comment by pascalpp** [comment]
hmm, looks like you might have a webpack issue, not an issue with this loader. does it work if you just do
`var image = require('../images/default-backimg.png');` ?

can you show more of your code, like where you're referencing the image variable after requiring it?

**Comment by wind4gis** [comment]
I fix it...
just write my load image code like...
     <pre>
     const img = new Image()      
      // img.addEventListener('load', e => {
      //   const srcImg = e.target
      //   resolve({ srcImg, img })
      // })
      img.onload = (e) => {
        console.log(img.width, img.height) // I can get the image dimension here... it's funny that I didn't have to use any tools... and It's more funny that I can't get image dimension by the addEventListener function...
        const srcImg = {height: img.height, width: img.width}
        resolve({ srcImg, img })
      }
      img.addEventListener('error', (err) => reject(err))
      img.src = url
</pre>

**Comment by wind4gis** [comment]
@pascalpp thank you, I will close this issue~
