### ISSUE TITLE
Webpack warnings - image-size-loader is trying to load my js files?

### ISSUE THREAD

**Issue by fresheneesz** [boopathi/image-size-loader#5]
I'm seeing a bunch of warnings in my webpack output now like this:

```
Warning: ./backend/~/image-size-loader!./backend/git/frontend/~/style/AssigneeDropdownStyle.js
Module build failed: TypeError: unsupported file type
    at lookup (/home/vagrant/backend/node_modules/image-size-loader/node_modules/image-size/lib/index.js:35:9)
    at module.exports (/home/vagrant/backend/node_modules/image-size-loader/node_modules/image-size/lib/index.js:101:12)
    at Object.module.exports (/home/vagrant/backend/node_modules/image-size-loader/index.js:41:15)
 @ ./backend/git/frontend/~/style ./backend/~/image-size-loader!^\.\/.*$
```

This is weird, cause I'm _only_ using `image-size-loader` explicitly for 2 png files. I didn't set up any automatic webpack config to detect file extensions. Any idea what could be going on here?

**Comment by boopathi** [comment]
You're trying to load a `js` file via image-size-loader, which is then passed on to `image-size` module.

`./backend/~/image-size-loader!./backend/git/frontend/~/style/`**`AssigneeDropdownStyle.js`**

**Comment by fresheneesz** [comment]
No I'm not doing that. Ohhh i see what its doing. I tried to make a function that processes this:

```
module.exports = function(name) {
    var image = require("image-size-loader!style/"+name)
    //...
}
```

And webpack is trying to bundle all the files in that folder.. I wish sokra would make its require parser just a liiiitle smarter.
